# Generated by Django 2.0.3 on 2018-03-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('adat', models.DateField()),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('obs', models.TextField()),
                ('reba', models.IntegerField()),
                ('rena', models.CharField(max_length=200)),
                ('stat', models.IntegerField()),
                ('final', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
