# Generated by Django 2.0.3 on 2018-04-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='adat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='obs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='rena',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
